In [4]:
import qdk
ctx = qdk.Context(project_root="../lib/")

headers=["n", "Ancilla (base)", "CCZ (base)", "Ancilla (new)", "CCZ (new)"]

table = []
for n in list(range(1,20))+list(range(20, 110, 10)) + [256]:
    op1 = "QuantumArithmetic.ConstAdder.AddConstant(1L,_)"
    re1 = ctx.logical_counts(f"EstimateUtils.RunUnaryOp({n},{op1})")
    op2 = "QuantumArithmetic.LAInc.IncrementByFlip"
    re2 = ctx.logical_counts(f"EstimateUtils.RunUnaryOp({n},{op2})")    
    table.append([n, re1["numQubits"]-n, re1["cczCount"], re2["numQubits"]-n, re2["cczCount"]])


import pandas as pd
pd.DataFrame(table, columns=headers)

      n  Ancilla (base)  CCZ (base)  Ancilla (new)  CCZ (new)
0     1               0           0              3          1
1     2               0           0              3          7
2     3               0           1              5         17
3     4               1           2              5         22
4     5               2           3              5         26
5     6               3           4              5         33
6     7               4           5              7         47
7     8               5           6              7         54
8     9               6           7              7         58
9    10               7           8              7         65
10   11               8           9              7         74
11   12               9          10              7         82
12   13              10          11              7         88
13   14              11          12              7         95
14   15              12          13              9        113
15   16              13          14              9        122
16   17              14          15              9        126
17   18              15          16              9        133
18   19              16          17              9        142
19   20              17          18              9        150
20   30              27          28              9        229
21   40              37          38             11        330
22   50              47          48             11        419
23   60              57          58             11        502
24   70              67          68             13        611
25   80              77          78             13        710
26   90              87          88             13        789
27  100              97          98             13        900
28  256             253         254             17       2554

In [6]:
headers=["n", "Ancilla (base)", "CCZ (base)", "Ancilla (new)", "CCZ (new)"]

table = []
for n in list(range(1,20))+list(range(20, 110, 10)) + [256]:
    op1 = "QuantumArithmetic.ConstAdder.AddConstant(1L,_)"
    re1 = ctx.logical_counts(f"EstimateUtils.RunUnaryOpCtl({n},{op1})")
    op2 = "QuantumArithmetic.LAInc.IncrementByFlip"
    re2 = ctx.logical_counts(f"EstimateUtils.RunUnaryOpCtl({n},{op2})")    
    table.append([n, re1["numQubits"]-(n+1), re1["cczCount"], re2["numQubits"]-(n+1), re2["cczCount"]])


import pandas as pd
pd.DataFrame(table, columns=headers)

      n  Ancilla (base)  CCZ (base)  Ancilla (new)  CCZ (new)
0     1               0           0              4          6
1     2               0           1              4         13
2     3               1           3              6         24
3     4               2           5              6         30
4     5               3           7              6         34
5     6               4           9              6         41
6     7               5          11              8         58
7     8               6          13              8         66
8     9               7          15              8         70
9    10               8          17              8         77
10   11               9          19              8         86
11   12              10          21              8         94
12   13              11          23              8        100
13   14              12          25              8        107
14   15              13          27             10        132
15   16              14          29             10        142
16   17              15          31             10        146
17   18              16          33             10        153
18   19              17          35             10        162
19   20              18          37             10        170
20   30              28          57             10        249
21   40              38          77             12        366
22   50              48          97             12        455
23   60              58         117             12        538
24   70              68         137             14        679
25   80              78         157             14        778
26   90              88         177             14        857
27  100              98         197             14        968
28  256             254         509             18       2814